---

- name: Consul Systemd Script
  template:
    src: "etc/systemd/system/consul.service.j2"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: "0755"
  when: ansible_service_mgr == "systemd"
  notify: systemd reload

- name: Consul Init Script
  template:
    src: "etc/init.d/consul.{{ansible_os_family}}.j2"
    dest: /etc/init.d/consul
    owner: root
    group: root
    mode: "0755"
  when: ansible_service_mgr != "systemd"

- name: Enable Consul at boot
  service:
    name: consul
    enabled: yes
    state: "{{ (consul_started|bool) | ternary('started', 'stopped')}}"
  when: consul_start_at_boot
