---

- name: systemd reload
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes
  when: consul_started

- name: consul start
  service:
    name: consul
    state: started
  when: consul_started
  tags: consul_start

- name: consul stop
  service:
    name: consul
    state: stopped
  tags: consul_stop

- name: consul restart
  service:
    name: consul
    state: restarted
  when: consul_started
  tags: consul_restart

- name: consul reload
  service:
    name: consul
    state: reloaded
  when: consul_started
  tags: consul_reload

# vi:ts=2:sw=2:et:ft=yaml
